### ISSUE TITLE
R36S - Salt and sanctuary only launches by FILEMANAGER

### ISSUE THREAD

**Issue by leld21** [JohnnyonFlame/FNAPatches#2]
Hi! installed the salt and sanctuary port on my r36s using 04-11-24 version of ArkOS. It launched fine on the PORTS executable until the screen of "saving automatically", then it crashes with some console prompts. I tried using the filemanager to launch the .sh file as i saw on a the portmaster discord message and it worked fine (nice fps btw, between 30-40). Is there a fix for this? why it doesnt work using the launcher on PORTS?

**Comment by JohnnyonFlame** [comment]
Please post the log file for both the successful and the failed launch.

**Comment by leld21** [comment]
Ok. Here are the two logs i got from salt and sanctury folder.
[crash log.txt](https://github.com/JohnnyonFlame/FNAPatches/files/15427612/crash.log.txt)
[success log.txt](https://github.com/JohnnyonFlame/FNAPatches/files/15427613/success.log.txt)

**Comment by JohnnyonFlame** [comment]
"Device or resource busy" is the same bug that happens on muOS - I think it's due to an application taking control of ALSA in the background and causing a resource starvation scenario.

The fix here I think is enabling `dmix` on your alsa config, it's an annoying ArkOS regression that keeps coming back over and over.

**Comment by leld21** [comment]
Got this working following this other issue on ArkOs. Basically the problem is what you said.
https://github.com/christianhaitian/arkos/issues/884
